export const ActionType = {
    AUTH_REQ: "AUTH_REQUEST",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAILURE: "AUTH_FAILUE",
    AUTH_LOGOUT: "AUTH_LOGOUT",
    USER_INFO_LOST: "USER_INFO_LOST",
    USER_INFO_FETCHED: "USER_INFO_FETCHED",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    CART_COUNTER_UPDATE: "CART_COUNTER_UPDATE"

} 